### ISSUE TITLE
leverage reactions for the majority of user feedback

### ISSUE THREAD

**Issue by Connoropolous** [metamaps/create-from-slack#1]
no need to send a written message when a thumbs up would suffice

**Comment by Bortseb** [comment]
Were you aware of this?
https://api.slack.com/docs/message-buttons

Can add buttons as an alternative to reactions for some things

**Comment by Connoropolous** [comment]
Yeah, totally. This Issue is actually for the inverse use case where I am wanting to indicate back to the user that metamapper has received their message and is in the process of responding to it

**Comment by Bortseb** [comment]
Ooops, accidentally hit close. :P

**Comment by Connoropolous** [comment]
use ⏳     : hourglass_flowing_sand :  for when commands you issued are loading
